import turtle

screen = turtle.Screen()
screen.screensize(500,500)
screen.bgcolor('paleturquoise')

t = turtle.Turtle()
t.speed(0)
#water
#t.penup()
#t.goto(-5000,-0)
#t.pendown()
#t.fillcolor('blue2')
#t.begin_fill()
#t.goto(5000,0)
#t.goto(5000,-150)
#t.goto(-5000,-150)
#t.goto(-5000,0)
#t.end_fill()
#greenland
t.penup()
t.goto(-5000,-100)
t.pendown()
t.pencolor('forestgreen')
t.fillcolor('forestgreen')
t.begin_fill()
t.goto(5000,-100)
t.goto(5000,-5000)
t.goto(-5000,-5000)
t.goto(-5000,-100)
t.end_fill()

t.penup()
t.pendown()
t.pencolor('brown')
t.pensize(5)
t.forward(100)
t.circle(20,180)


t.penup()
t.goto(-200,-80)
t.pendown()
t.pensize(15)
t.goto(-200,0)

#tree
t.penup()
t.setheading(0)
t.goto(-200,0)
t.pendown()
t.pensize(1)
t.fillcolor('forestgreen')
t.pencolor('forestgreen')
t.begin_fill()
t.circle(30)
t.end_fill()
t.penup()
t.setheading(0)
t.goto(-220,-10)
t.pendown()
t.pensize(1)
t.fillcolor('forestgreen')
t.begin_fill()
t.circle(30)
t.end_fill()
t.penup()
t.setheading(0)
t.goto(-190,-10)
t.pendown()
t.pensize(1)
t.fillcolor('forestgreen')
t.begin_fill()
t.circle(30)
t.end_fill()
#pond
t.penup()
t.setheading(0)
t.goto(0,-300)
t.fillcolor('blue')
t.begin_fill()
t.circle(50)
t.end_fill()
#sun
t.penup()
t.setheading(0)
t.goto(250,300)
t.fillcolor('yellow')
t.begin_fill()
t.circle(80)
t.end_fill()
t.hideturtle()
#Apple
t.penup()
t.setheading(0)
t.goto(30,-100)
t.fillcolor('red')
t.begin_fill()
t.circle(10)
t.end_fill()



turtle.done()